BEGIN;
CREATE TYPE "RoleName_new" AS ENUM ('SOLICITANTE', 'COMPRADOR', 'APROVADOR', 'JURIDICO', 'TESOURARIA', 'CONTROLADORIA', 'PRIVACIDADE', 'FISCAL', 'ADMIN', 'COORDENACAO', 'GERENTE_FNC');
ALTER TABLE "UserRole" ALTER COLUMN "role" TYPE "RoleName_new" USING ("role"::text::"RoleName_new");
ALTER TYPE "RoleName" RENAME TO "RoleName_old";
ALTER TYPE "RoleName_new" RENAME TO "RoleName";
DROP TYPE "RoleName_old";
COMMIT;
